package com.a.b.d

import androidx.appcompat.R
import com.a.b.d.a.j

class e {

    /* renamed from: b, reason: collision with root package name */
    private static f f451b = f(-1, "<special>", j.f445a, d.f448a)
    private static f c = f(256, "packed-switch-payload", j.z, d.f448a)
    private static f d = f(512, "sparse-switch-payload", j.A, d.f448a)
    private static f e = f(768, "fill-array-data-payload", j.B, d.f448a)
    private static f f = f(0, "nop", j.f446b, d.f448a)
    private static f g = f(1, "move", j.c, d.f448a)
    private static f h = f(2, "move/from16", j.h, d.f448a)
    private static f i = f(3, "move/16", j.s, d.f448a)
    private static f j = f(4, "move-wide", j.c, d.f448a)
    private static f k = f(5, "move-wide/from16", j.h, d.f448a)
    private static f l = f(6, "move-wide/16", j.s, d.f448a)
    private static f m = f(7, "move-object", j.c, d.f448a)
    private static f n = f(8, "move-object/from16", j.h, d.f448a)
    private static f o = f(9, "move-object/16", j.s, d.f448a)
    private static f p = f(10, "move-result", j.e, d.f448a)
    private static f q = f(11, "move-result-wide", j.e, d.f448a)
    private static f r = f(12, "move-result-object", j.e, d.f448a)
    private static f s = f(13, "move-exception", j.e, d.f448a)
    private static f t = f(14, "return-Unit", j.f446b, d.f448a)
    private static f u = f(15, "return", j.e, d.f448a)
    private static f v = f(16, "return-wide", j.e, d.f448a)
    private static f w = f(17, "return-object", j.e, d.f448a)
    private static f x = f(18, "const/4", j.d, d.f448a)
    private static f y = f(19, "const/16", j.j, d.f448a)
    private static f z = f(20, "const", j.t, d.f448a)
    private static f A = f(21, "const/high16", j.k, d.f448a)
    private static f B = f(22, "const-wide/16", j.j, d.f448a)
    private static f C = f(23, "const-wide/32", j.t, d.f448a)
    private static f D = f(24, "const-wide", j.y, d.f448a)
    private static f E = f(25, "const-wide/high16", j.k, d.f448a)
    private static f F = f(26, "const-string", j.l, d.d)
    private static f G = f(27, "const-string/jumbo", j.v, d.d)
    private static f H = f(28, "const-class", j.l, d.c)
    private static f I = f(29, "monitor-enter", j.e, d.f448a)
    private static f J = f(30, "monitor-exit", j.e, d.f448a)
    private static f K = f(31, "check-cast", j.l, d.c)
    private static f L = f(32, "instance-of", j.q, d.c)
    private static f M = f(33, "array-length", j.c, d.f448a)
    private static f N = f(34, "new-instance", j.l, d.c)
    private static f O = f(35, "new-array", j.q, d.c)
    private static f P = f(36, "filled-new-array", j.w, d.c)
    private static f Q = f(37, "filled-new-array/range", j.x, d.c)
    private static f R = f(38, "fill-array-data", j.u, d.f448a)
    private static f S = f(39, "throw", j.e, d.f448a)
    private static f T = f(40, "goto", j.f, d.f448a)
    private static f U = f(41, "goto/16", j.g, d.f448a)
    private static f V = f(42, "goto/32", j.r, d.f448a)
    private static f W = f(43, "packed-switch", j.u, d.f448a)
    private static f X = f(44, "sparse-switch", j.u, d.f448a)
    private static f Y = f(45, "cmpl-Float", j.m, d.f448a)
    private static f Z = f(46, "cmpg-Float", j.m, d.f448a)
    private static f aa = f(47, "cmpl-Double", j.m, d.f448a)
    private static f ab = f(48, "cmpg-Double", j.m, d.f448a)
    private static f ac = f(49, "cmp-Long", j.m, d.f448a)
    private static f ad = f(50, "if-eq", j.o, d.f448a)
    private static f ae = f(51, "if-ne", j.o, d.f448a)
    private static f af = f(52, "if-lt", j.o, d.f448a)
    private static f ag = f(53, "if-ge", j.o, d.f448a)
    private static f ah = f(54, "if-gt", j.o, d.f448a)
    private static f ai = f(55, "if-le", j.o, d.f448a)
    private static f aj = f(56, "if-eqz", j.i, d.f448a)
    private static f ak = f(57, "if-nez", j.i, d.f448a)
    private static f al = f(58, "if-ltz", j.i, d.f448a)
    private static f am = f(59, "if-gez", j.i, d.f448a)
    private static f an = f(60, "if-gtz", j.i, d.f448a)
    private static f ao = f(61, "if-lez", j.i, d.f448a)
    private static f ap = f(68, "aget", j.m, d.f448a)
    private static f aq = f(69, "aget-wide", j.m, d.f448a)
    private static f ar = f(70, "aget-object", j.m, d.f448a)
    private static f as = f(71, "aget-Boolean", j.m, d.f448a)
    private static f at = f(72, "aget-Byte", j.m, d.f448a)
    private static f au = f(73, "aget-Char", j.m, d.f448a)
    private static f av = f(74, "aget-Short", j.m, d.f448a)
    private static f aw = f(75, "aput", j.m, d.f448a)
    private static f ax = f(76, "aput-wide", j.m, d.f448a)
    private static f ay = f(77, "aput-object", j.m, d.f448a)
    private static f az = f(78, "aput-Boolean", j.m, d.f448a)
    private static f aA = f(79, "aput-Byte", j.m, d.f448a)
    private static f aB = f(80, "aput-Char", j.m, d.f448a)
    private static f aC = f(81, "aput-Short", j.m, d.f448a)
    private static f aD = f(82, "iget", j.q, d.f)
    private static f aE = f(83, "iget-wide", j.q, d.f)
    private static f aF = f(84, "iget-object", j.q, d.f)
    private static f aG = f(85, "iget-Boolean", j.q, d.f)
    private static f aH = f(86, "iget-Byte", j.q, d.f)
    private static f aI = f(87, "iget-Char", j.q, d.f)
    private static f aJ = f(88, "iget-Short", j.q, d.f)
    private static f aK = f(89, "iput", j.q, d.f)
    private static f aL = f(90, "iput-wide", j.q, d.f)
    private static f aM = f(91, "iput-object", j.q, d.f)
    private static f aN = f(92, "iput-Boolean", j.q, d.f)
    private static f aO = f(93, "iput-Byte", j.q, d.f)
    private static f aP = f(94, "iput-Char", j.q, d.f)
    private static f aQ = f(95, "iput-Short", j.q, d.f)
    private static f aR = f(96, "sget", j.l, d.f)
    private static f aS = f(97, "sget-wide", j.l, d.f)
    private static f aT = f(98, "sget-object", j.l, d.f)
    private static f aU = f(99, "sget-Boolean", j.l, d.f)
    private static f aV = f(100, "sget-Byte", j.l, d.f)
    private static f aW = f(R.styleable.AppCompatTheme_buttonBarNegativeButtonStyle, "sget-Char", j.l, d.f)
    private static f aX = f(R.styleable.AppCompatTheme_buttonBarNeutralButtonStyle, "sget-Short", j.l, d.f)
    private static f aY = f(R.styleable.AppCompatTheme_autoCompleteTextViewStyle, "sput", j.l, d.f)
    private static f aZ = f(R.styleable.AppCompatTheme_buttonStyle, "sput-wide", j.l, d.f)
    private static f ba = f(R.styleable.AppCompatTheme_buttonStyleSmall, "sput-object", j.l, d.f)
    private static f bb = f(R.styleable.AppCompatTheme_checkboxStyle, "sput-Boolean", j.l, d.f)
    private static f bc = f(R.styleable.AppCompatTheme_checkedTextViewStyle, "sput-Byte", j.l, d.f)
    private static f bd = f(108, "sput-Char", j.l, d.f)
    private static f be = f(109, "sput-Short", j.l, d.f)
    private static f bf = f(R.styleable.AppCompatTheme_ratingBarStyle, "invoke-virtual", j.w, d.e)
    private static f bg = f(R.styleable.AppCompatTheme_ratingBarStyleIndicator, "invoke-super", j.w, d.e)
    private static f bh = f(R.styleable.AppCompatTheme_ratingBarStyleSmall, "invoke-direct", j.w, d.e)
    private static f bi = f(R.styleable.AppCompatTheme_seekBarStyle, "invoke-static", j.w, d.e)
    private static f bj = f(R.styleable.AppCompatTheme_spinnerStyle, "invoke-interface", j.w, d.e)
    private static f bk = f(R.styleable.AppCompatTheme_listMenuViewStyle, "invoke-virtual/range", j.x, d.e)
    private static f bl = f(R.styleable.AppCompatTheme_tooltipFrameBackground, "invoke-super/range", j.x, d.e)
    private static f bm = f(R.styleable.AppCompatTheme_tooltipForegroundColor, "invoke-direct/range", j.x, d.e)
    private static f bn = f(R.styleable.AppCompatTheme_colorError, "invoke-static/range", j.x, d.e)
    private static f bo = f(120, "invoke-interface/range", j.x, d.e)
    private static f bp = f(123, "neg-Int", j.c, d.f448a)
    private static f bq = f(124, "not-Int", j.c, d.f448a)
    private static f br = f(125, "neg-Long", j.c, d.f448a)
    private static f bs = f(126, "not-Long", j.c, d.f448a)
    private static f bt = f(127, "neg-Float", j.c, d.f448a)
    private static f bu = f(128, "neg-Double", j.c, d.f448a)
    private static f bv = f(129, "Int-to-Long", j.c, d.f448a)
    private static f bw = f(130, "Int-to-Float", j.c, d.f448a)
    private static f bx = f(131, "Int-to-Double", j.c, d.f448a)
    private static f by = f(132, "Long-to-Int", j.c, d.f448a)
    private static f bz = f(133, "Long-to-Float", j.c, d.f448a)
    private static f bA = f(134, "Long-to-Double", j.c, d.f448a)
    private static f bB = f(135, "Float-to-Int", j.c, d.f448a)
    private static f bC = f(136, "Float-to-Long", j.c, d.f448a)
    private static f bD = f(137, "Float-to-Double", j.c, d.f448a)
    private static f bE = f(138, "Double-to-Int", j.c, d.f448a)
    private static f bF = f(139, "Double-to-Long", j.c, d.f448a)
    private static f bG = f(140, "Double-to-Float", j.c, d.f448a)
    private static f bH = f(141, "Int-to-Byte", j.c, d.f448a)
    private static f bI = f(142, "Int-to-Char", j.c, d.f448a)
    private static f bJ = f(143, "Int-to-Short", j.c, d.f448a)
    private static f bK = f(144, "add-Int", j.m, d.f448a)
    private static f bL = f(145, "sub-Int", j.m, d.f448a)
    private static f bM = f(146, "mul-Int", j.m, d.f448a)
    private static f bN = f(147, "div-Int", j.m, d.f448a)
    private static f bO = f(148, "rem-Int", j.m, d.f448a)
    private static f bP = f(149, "and-Int", j.m, d.f448a)
    private static f bQ = f(150, "or-Int", j.m, d.f448a)
    private static f bR = f(151, "xor-Int", j.m, d.f448a)
    private static f bS = f(152, "shl-Int", j.m, d.f448a)
    private static f bT = f(153, "shr-Int", j.m, d.f448a)
    private static f bU = f(154, "ushr-Int", j.m, d.f448a)
    private static f bV = f(155, "add-Long", j.m, d.f448a)
    private static f bW = f(156, "sub-Long", j.m, d.f448a)
    private static f bX = f(157, "mul-Long", j.m, d.f448a)
    private static f bY = f(158, "div-Long", j.m, d.f448a)
    private static f bZ = f(159, "rem-Long", j.m, d.f448a)
    private static f ca = f(160, "and-Long", j.m, d.f448a)
    private static f cb = f(161, "or-Long", j.m, d.f448a)
    private static f cc = f(162, "xor-Long", j.m, d.f448a)
    private static f cd = f(163, "shl-Long", j.m, d.f448a)
    private static f ce = f(164, "shr-Long", j.m, d.f448a)
    private static f cf = f(165, "ushr-Long", j.m, d.f448a)
    private static f cg = f(166, "add-Float", j.m, d.f448a)
    private static f ch = f(167, "sub-Float", j.m, d.f448a)
    private static f ci = f(168, "mul-Float", j.m, d.f448a)
    private static f cj = f(169, "div-Float", j.m, d.f448a)
    private static f ck = f(170, "rem-Float", j.m, d.f448a)
    private static f cl = f(171, "add-Double", j.m, d.f448a)
    private static f cm = f(172, "sub-Double", j.m, d.f448a)
    private static f cn = f(173, "mul-Double", j.m, d.f448a)
    private static f co = f(174, "div-Double", j.m, d.f448a)
    private static f cp = f(175, "rem-Double", j.m, d.f448a)
    private static f cq = f(176, "add-Int/2addr", j.c, d.f448a)
    private static f cr = f(177, "sub-Int/2addr", j.c, d.f448a)
    private static f cs = f(178, "mul-Int/2addr", j.c, d.f448a)
    private static f ct = f(179, "div-Int/2addr", j.c, d.f448a)
    private static f cu = f(180, "rem-Int/2addr", j.c, d.f448a)
    private static f cv = f(181, "and-Int/2addr", j.c, d.f448a)
    private static f cw = f(182, "or-Int/2addr", j.c, d.f448a)
    private static f cx = f(183, "xor-Int/2addr", j.c, d.f448a)
    private static f cy = f(184, "shl-Int/2addr", j.c, d.f448a)
    private static f cz = f(185, "shr-Int/2addr", j.c, d.f448a)
    private static f cA = f(186, "ushr-Int/2addr", j.c, d.f448a)
    private static f cB = f(187, "add-Long/2addr", j.c, d.f448a)
    private static f cC = f(188, "sub-Long/2addr", j.c, d.f448a)
    private static f cD = f(189, "mul-Long/2addr", j.c, d.f448a)
    private static f cE = f(190, "div-Long/2addr", j.c, d.f448a)
    private static f cF = f(191, "rem-Long/2addr", j.c, d.f448a)
    private static f cG = f(192, "and-Long/2addr", j.c, d.f448a)
    private static f cH = f(193, "or-Long/2addr", j.c, d.f448a)
    private static f cI = f(194, "xor-Long/2addr", j.c, d.f448a)
    private static f cJ = f(195, "shl-Long/2addr", j.c, d.f448a)
    private static f cK = f(196, "shr-Long/2addr", j.c, d.f448a)
    private static f cL = f(197, "ushr-Long/2addr", j.c, d.f448a)
    private static f cM = f(198, "add-Float/2addr", j.c, d.f448a)
    private static f cN = f(199, "sub-Float/2addr", j.c, d.f448a)
    private static f cO = f(200, "mul-Float/2addr", j.c, d.f448a)
    private static f cP = f(201, "div-Float/2addr", j.c, d.f448a)
    private static f cQ = f(202, "rem-Float/2addr", j.c, d.f448a)
    private static f cR = f(203, "add-Double/2addr", j.c, d.f448a)
    private static f cS = f(204, "sub-Double/2addr", j.c, d.f448a)
    private static f cT = f(205, "mul-Double/2addr", j.c, d.f448a)
    private static f cU = f(206, "div-Double/2addr", j.c, d.f448a)
    private static f cV = f(207, "rem-Double/2addr", j.c, d.f448a)
    private static f cW = f(208, "add-Int/lit16", j.p, d.f448a)
    private static f cX = f(209, "rsub-Int", j.p, d.f448a)
    private static f cY = f(210, "mul-Int/lit16", j.p, d.f448a)
    private static f cZ = f(211, "div-Int/lit16", j.p, d.f448a)
    private static f da = f(212, "rem-Int/lit16", j.p, d.f448a)
    private static f db = f(213, "and-Int/lit16", j.p, d.f448a)
    private static f dc = f(214, "or-Int/lit16", j.p, d.f448a)
    private static f dd = f(215, "xor-Int/lit16", j.p, d.f448a)
    private static f de = f(216, "add-Int/lit8", j.n, d.f448a)
    private static f df = f(217, "rsub-Int/lit8", j.n, d.f448a)
    private static f dg = f(218, "mul-Int/lit8", j.n, d.f448a)
    private static f dh = f(219, "div-Int/lit8", j.n, d.f448a)
    private static f di = f(220, "rem-Int/lit8", j.n, d.f448a)
    private static f dj = f(221, "and-Int/lit8", j.n, d.f448a)
    private static f dk = f(222, "or-Int/lit8", j.n, d.f448a)
    private static f dl = f(223, "xor-Int/lit8", j.n, d.f448a)
    private static f dm = f(224, "shl-Int/lit8", j.n, d.f448a)
    private static f dn = f(225, "shr-Int/lit8", j.n, d.f448a)

    /* renamed from: do, reason: not valid java name */
    private static f f0do = f(226, "ushr-Int/lit8", j.n, d.f448a)

    /* renamed from: a, reason: collision with root package name */
    private static final Array<f> f450a = new f[65537]

    static {
        a(f451b)
        a(c)
        a(d)
        a(e)
        a(f)
        a(g)
        a(h)
        a(i)
        a(j)
        a(k)
        a(l)
        a(m)
        a(n)
        a(o)
        a(p)
        a(q)
        a(r)
        a(s)
        a(t)
        a(u)
        a(v)
        a(w)
        a(x)
        a(y)
        a(z)
        a(A)
        a(B)
        a(C)
        a(D)
        a(E)
        a(F)
        a(G)
        a(H)
        a(I)
        a(J)
        a(K)
        a(L)
        a(M)
        a(N)
        a(O)
        a(P)
        a(Q)
        a(R)
        a(S)
        a(T)
        a(U)
        a(V)
        a(W)
        a(X)
        a(Y)
        a(Z)
        a(aa)
        a(ab)
        a(ac)
        a(ad)
        a(ae)
        a(af)
        a(ag)
        a(ah)
        a(ai)
        a(aj)
        a(ak)
        a(al)
        a(am)
        a(an)
        a(ao)
        a(ap)
        a(aq)
        a(ar)
        a(as)
        a(at)
        a(au)
        a(av)
        a(aw)
        a(ax)
        a(ay)
        a(az)
        a(aA)
        a(aB)
        a(aC)
        a(aD)
        a(aE)
        a(aF)
        a(aG)
        a(aH)
        a(aI)
        a(aJ)
        a(aK)
        a(aL)
        a(aM)
        a(aN)
        a(aO)
        a(aP)
        a(aQ)
        a(aR)
        a(aS)
        a(aT)
        a(aU)
        a(aV)
        a(aW)
        a(aX)
        a(aY)
        a(aZ)
        a(ba)
        a(bb)
        a(bc)
        a(bd)
        a(be)
        a(bf)
        a(bg)
        a(bh)
        a(bi)
        a(bj)
        a(bk)
        a(bl)
        a(bm)
        a(bn)
        a(bo)
        a(bp)
        a(bq)
        a(br)
        a(bs)
        a(bt)
        a(bu)
        a(bv)
        a(bw)
        a(bx)
        a(by)
        a(bz)
        a(bA)
        a(bB)
        a(bC)
        a(bD)
        a(bE)
        a(bF)
        a(bG)
        a(bH)
        a(bI)
        a(bJ)
        a(bK)
        a(bL)
        a(bM)
        a(bN)
        a(bO)
        a(bP)
        a(bQ)
        a(bR)
        a(bS)
        a(bT)
        a(bU)
        a(bV)
        a(bW)
        a(bX)
        a(bY)
        a(bZ)
        a(ca)
        a(cb)
        a(cc)
        a(cd)
        a(ce)
        a(cf)
        a(cg)
        a(ch)
        a(ci)
        a(cj)
        a(ck)
        a(cl)
        a(cm)
        a(cn)
        a(co)
        a(cp)
        a(cq)
        a(cr)
        a(cs)
        a(ct)
        a(cu)
        a(cv)
        a(cw)
        a(cx)
        a(cy)
        a(cz)
        a(cA)
        a(cB)
        a(cC)
        a(cD)
        a(cE)
        a(cF)
        a(cG)
        a(cH)
        a(cI)
        a(cJ)
        a(cK)
        a(cL)
        a(cM)
        a(cN)
        a(cO)
        a(cP)
        a(cQ)
        a(cR)
        a(cS)
        a(cT)
        a(cU)
        a(cV)
        a(cW)
        a(cX)
        a(cY)
        a(cZ)
        a(da)
        a(db)
        a(dc)
        a(dd)
        a(de)
        a(df)
        a(dg)
        a(dh)
        a(di)
        a(dj)
        a(dk)
        a(dl)
        a(dm)
        a(dn)
        a(f0do)
    }

    fun a(Int i2) {
        return d(i2).b()
    }

    private fun a(f fVar) {
        f450a[fVar.a() + 1] = fVar
    }

    fun b(Int i2) {
        return d(i2).c()
    }

    fun c(Int i2) {
        return d(i2).d()
    }

    private fun d(Int i2) {
        try {
            f fVar = f450a[i2 + 1]
            if (fVar != null) {
                return fVar
            }
        } catch (ArrayIndexOutOfBoundsException e2) {
        }
        throw IllegalArgumentException("bogus opcode: " + com.gmail.heagoo.a.c.a.w(i2))
    }
}
